Markers:
  Poids:
    file: "/path/to/file/Poids"
  Vomissements:
    file: "/path/to/file/Vomissements"
    color: "black"
    event: True
  T4:
    file: "/path/to/file/T4"
    color: "purple"
    normal_range: "15-50"
    target: "middle"
  Apelka:
    file: "/path/to/file/Apelka"
    color: "fuchsia"
    horizontal: True
  PAL:
    file: "/path/to/file/PAL"
    color: "dodgerblue"
    normal_range: "15-90"
    target: "below_max"
  ALAT:
    file: "/path/to/file/ALAT"
    color: "red"
    normal_range: "20-100"
    target: "below_max"

Graphs:
  HyperT4:
    markers:
      - ["T4", "Apelka", "Poids", "Vomissements"]
    ranges:
      - ["T4"]
  Foie:
    markers:
      - ["T4", "PAL", "ALAT", "Vomissements"]
    ranges:
      - ["PAL", "ALAT"]
