Markers:
  Poids:
    color: "#289228"
    file: "/path/to/file/Poids"
  Vomissements:
    file: "/path/to/file/Vomissements"
    color: "black"
    event: True
  T4:
    file: "/path/to/file/T4"
    color: "purple"
    normal_range: "15-50"
    target: "middle"
  Apelka:
    file: "/path/to/file/Apelka"
    color: "#7e66fe"
    horizontal: True
  Hématocrite:
    file: "/path/to/file/Hématocrite"
    color: "red"
    normal_range: "33.7-45"
    target: "above_min"
  PAL:
    file: "/path/to/file/PAL"
    color: "red"
    normal_range: "15-90"
    target: "below_max"
  ALAT:
    file: "/path/to/file/ALAT"
    color: "#124cff"
    normal_range: "20-100"
    target: "below_max"

Modifications:
  file: "/path/to/file/Modifications"
  colors:
    "T4": "purple"
    "foie": "#124cff"
    "reins": "#ff6600"

Graphs:
  HyperT4:
    markers:
      - ["T4", "Apelka", "Hématocrite", "Poids", "Vomissements"]
    ranges:
      - ["T4", "Hématocrite"]
    modifications: "all"
  Foie:
    markers:
      - ["T4", "PAL", "ALAT", "Vomissements"]
    ranges:
      - ["PAL", "ALAT"]
    modifications: "foie"
